# Generated by Django 6.0.5 on 2026-05-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee'), ('Desserts', 'Desserts')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
